### ISSUE TITLE
Spaceball support should be optional

### ISSUE THREAD

**Issue by rootlm** [freeglut/freeglut#176]
Freeglut errors on Windows 98 because the Spaceball code uses RawInput. Just replacing it with the stubs from the Wayland backend and removing the call in fg_main_mswin.c made the demos work fine (except the OpenGL 3 and Spaceball ones of course) so I think a CMake option should be added to disable it.

**Comment by dcnieho** [comment]
Please provide a patch

**Comment by jtsiomb** [comment]
We should probably have cmake detect if RawInput is available, and make the code that uses it conditional on its availability, instead of just adding an option to arbitrarilly disable spaceball support.

**Comment by jtsiomb** [comment]
Also ideally we should rely on the 3Dconnexion driver, instead of trying to use the device directly, which would widen compatibility with different spacemice. For instance on a win98 machine with period 3Dconnexion drivers it should be possible to use serial devices too, which can't be reliably auto-detected and used by freeglut otherwise.

I'll put it in my TODO list to see if we can talk to the driver by dynamically loading their dll if it's installed, but it'll probably take me a long time to get to that.

**Comment by jtsiomb** [comment]
I noticed the mswin/spaceball source file is already ifdef-ed to build only on winXP or higher. I assume the issue was that it fails to provide empty functions in an `#else` block which causes linker errors. I attempted to fix that blindly in the last commit, @rootlm can you try it and let me know if it fixes the build on win98 of if there's something else I missed?

**Comment by rootlm** [comment]
Apparently I pull requested #177  right after you made your changes. I think that would fix building on old Visual Studio versions, but I'm using MinGW which only runs on XP+ which is why I think a CMake option would make more sense.

**Comment by jtsiomb** [comment]
Unless we have no other recourse, I don't like an option which just disables a random feature.

Is the problem a runtime error? So you can build with mingw a version of freeglut which would otherwise work on win98, but msvcrt.dll on win98 doesn't have the necessary functions and fails to load at runtime?

**Comment by rootlm** [comment]
Yeah, it's a runtime error, GetRawInputData/etc are missing from user32.dll.

**Comment by rcmaniac25** [comment]
Looking through the last GLUT version (3.7) I see a number of comments basically saying "spaceball isn't supported on windows as of this time" (readme from 1997).

I think a cmake option makes sense. Enabled by default, ifdef defines if it's supported, but then also check the cmake flag.

**Comment by jtsiomb** [comment]
I'll look into it, give me a couple of days, I think I had a windows machine somewhere around here

**Comment by jtsiomb** [comment]
@rootlm can you try the last commit and let me know if it fixes the issue when running on win98 ?

**Comment by rootlm** [comment]
Yep, that appears to fix it.
