### ISSUE TITLE
Missing macro GLUT_KEY_TAB

### ISSUE THREAD

**Issue by qfcy** [freeglut/freeglut#190]
I've searched through all the header files (.h) and found that the GLUT_KEY_TAB macro is missing. Therefore, I propose to add it. 
```cpp
#define GLUT_KEY_TAB 0x9
```
Additionally, I hope other key macros could be added: 
```cpp
#define GLUT_KEY_ESC 0x1b
#define GLUT_KEY_ENTER 0x0c // also referred to as GLUT_KEY_RETURN in the community
```
(Note that `GLUT_KEY_TAB` can be handled with `glutKeyboardFunc`, not `glutSpecialFunc`. )

**Comment by jtsiomb** [comment]
I wouldn't call it "missing", since it wasn't in original GLUT either, and one can just use `'\t'`.

As you indirectly pointed out, all the other GLUT_KEY_* defines are for keys handled by the special callback. So I'm not sure if adding regular key defines will be helpful or confusing  (GLUT_KEY_TAB and GLUT_KEY_F9 both being defined as 9).

I'm leaning towards adding it being mostly harmless, but I'd like to hear other opinions.

**Comment by dcnieho** [comment]
I don't see the point of it, as indeed, like any other character, you don't need a define for this. There is no `GLUT_KEY_A` etc either. I think I'd be rather arbitrary to add this (or a few) keys, and it leads to an inconsistent API. So i'd say no.

**Comment by qfcy** [comment]
ok😂
